In [ ]:
# Required Lbnrary
import pandas as pd
import numpy as np
from dateutil.parser import parse
from google.colab import files

In [ ]:
# Get access to connect to Google Drive
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
# Getting data from link drive 
# Harapan lama sekolah
# https://docs.google.com/spreadsheets/d/1rWpZWoFbyVhXbBRIt8EVr6LktL8lRMUl/edit?usp=sharing&ouid=112728685642656103452&rtpof=true&sd=true
fileDownloaded1 = drive.CreateFile({'id':'1rWpZWoFbyVhXbBRIt8EVr6LktL8lRMUl'})
fileDownloaded1.GetContentFile('Harapan Lama Sekolah.xlsx')

# Pengeluaran pendapatan per kapita yang disesuaikan
# https://docs.google.com/spreadsheets/d/1Xiy0bCUzkNjIULuOSc4FcJwaFoKdmn8g/edit?usp=sharing&ouid=112728685642656103452&rtpof=true&sd=true
fileDownloaded2 = drive.CreateFile({'id':'1Xiy0bCUzkNjIULuOSc4FcJwaFoKdmn8g'})
fileDownloaded2.GetContentFile('Pengeluaran per Kapita Disesuaikan.xlsx')

# Rata-rata lama sekolah
# https://docs.google.com/spreadsheets/d/1SzYAmuU5eGHG8lQ2_36LjGp-r5tFz1wr/edit?usp=sharing&ouid=112728685642656103452&rtpof=true&sd=true
fileDownloaded3 = drive.CreateFile({'id':'1SzYAmuU5eGHG8lQ2_36LjGp-r5tFz1wr'})
fileDownloaded3.GetContentFile('Rata-rata Lama Sekolah.xlsx')

# Umur Harapan Hidup Saat Lahir (UHH)
# https://docs.google.com/spreadsheets/d/1vTfPVZ00mTN5oUoBSOIEGJwt7GNy959T/edit?usp=sharing&ouid=112728685642656103452&rtpof=true&sd=true
fileDownloaded4 = drive.CreateFile({'id':'1vTfPVZ00mTN5oUoBSOIEGJwt7GNy959T'})
fileDownloaded4.GetContentFile('Umur Harapan Hidup Saat Lahir (UHH).xlsx')

# IPM
# https://docs.google.com/spreadsheets/d/1o0DrErjKwlY2bwhkuSnLzF9TTgD1npZi/edit?usp=sharing&ouid=112728685642656103452&rtpof=true&sd=true
fileDownloaded5 = drive.CreateFile({'id':'1o0DrErjKwlY2bwhkuSnLzF9TTgD1npZi'})
fileDownloaded5.GetContentFile('Indeks Pembangunan Manusia.xlsx')

# LatLong
# https://docs.google.com/spreadsheets/d/1uVfDX3bNi5kTXMIE2DRKTV40qzqmygfD/edit?usp=sharing&ouid=112728685642656103452&rtpof=true&sd=true
fileDownloaded6 = drive.CreateFile({'id':'1uVfDX3bNi5kTXMIE2DRKTV40qzqmygfD'})
fileDownloaded6.GetContentFile('LatLong.xlsx')

In [ ]:
# add new column with certain value
df1= pd.read_excel('Harapan Lama Sekolah.xlsx')
df1['Komponen'] = 'Harapan Lama Sekolah'

df2 = pd.read_excel('Pengeluaran per Kapita Disesuaikan.xlsx')
df2['Komponen'] = 'Pengeluaran per Kapita Disesuaikan'

df3 = pd.read_excel('Rata-rata Lama Sekolah.xlsx')
df3['Komponen'] = 'Rata-rata Lama Sekolah'

df4 = pd.read_excel('Umur Harapan Hidup Saat Lahir (UHH).xlsx')
df4['Komponen'] = 'Umur Harapan Hidup Saat Lahir'

df5 = pd.read_excel('Indeks Pembangunan Manusia.xlsx')
df5['Komponen'] = 'Indeks Pembangunan Manusia'

df6 = pd.read_excel('LatLong.xlsx')

In [ ]:
# Convert uppercase to title style


df1['Provinsi/Kabupaten/Kota'] = df1['Provinsi/Kabupaten/Kota'].str.title()
df2['Provinsi/Kabupaten/Kota'] = df2['Provinsi/Kabupaten/Kota'].str.title()
df3['Provinsi/Kabupaten/Kota'] = df3['Provinsi/Kabupaten/Kota'].str.title()
df4['Provinsi/Kabupaten/Kota'] = df4['Provinsi/Kabupaten/Kota'].str.title()
df5['Provinsi/Kabupaten/Kota'] = df5['Provinsi/Kabupaten/Kota'].str.title()

df6['Provinsi/Kabupaten/Kota'] = df6['Provinsi/Kabupaten/Kota'].str.replace('KABUPATEN ', '')
df6['Provinsi/Kabupaten/Kota'] = df6['Provinsi/Kabupaten/Kota'].str.title()

df1= pd.merge(df1, df6, on ='Provinsi/Kabupaten/Kota', how ="left")
df2= pd.merge(df2, df6, on ='Provinsi/Kabupaten/Kota', how ="left")
df3= pd.merge(df3, df6, on ='Provinsi/Kabupaten/Kota', how ="left")
df4= pd.merge(df4, df6, on ='Provinsi/Kabupaten/Kota', how ="left")
df5= pd.merge(df5, df6, on ='Provinsi/Kabupaten/Kota', how ="left")


# Concat all data
df_full = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)
df_full['Provinsi'] = df_full['Provinsi'].str.title()

In [ ]:
df_full

,Provinsi/Kabupaten/Kota,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Provinsi,Regional,Komponen,latitude,longitude
0,Aceh,12.9,13.03,13.19,13.36,13.53,13.73,13.89,14.13,14.27,14.30,14.31,14.36,Aceh,Provinsi,Harapan Lama Sekolah,4.36855,97.025300
1,Simeulue,12.45,12.66,12.67,12.67,12.75,12.83,13.07,13.23,13.25,13.51,13.76,13.90,Aceh,Kab/Kota,Harapan Lama Sekolah,2.61667,96.083330
2,Aceh Singkil,12.41,12.84,13.49,13.85,14.05,14.26,14.27,14.28,14.29,14.30,14.31,14.32,Aceh,Kab/Kota,Harapan Lama Sekolah,2.41667,97.916670
3,Aceh Selatan,12.35,12.51,12.57,13.01,13.05,13.24,13.53,13.80,14.15,14.41,14.42,14.60,Aceh,Kab/Kota,Harapan Lama Sekolah,3.16667,97.416670
4,Aceh Tenggara,12.43,12.66,13.18,13.54,13.59,13.62,13.96,13.97,13.98,13.99,14.00,14.01,Aceh,Kab/Kota,Harapan Lama Sekolah,3.36667,97.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2740,Dogiyai,47.48,48.48,50.59,51.46,52.25,52.78,53.32,54.04,54.44,55.41,54.84,55.00,Papua,Kab/Kota,Indeks Pembangunan Manusia,-4.03186,135.439450
2741,Intan Jaya,0.0,40.07,41.89,42.69,43.51,44.35,44.82,45.68,46.55,47.51,47.79,48.34,Papua,Kab/Kota,Indeks Pembangunan Manusia,-3.41016,136.708370
2742,Deiyai,0.0,46.12,46.94,47.74,48.12,48.28,48.50,49.07,49.55,50.11,49.46,49.96,Papua,Kab/Kota,Indeks Pembangunan Manusia,-3.94737,135.950320
2743,Kota Jayapura,76.69,76.97,77.25,77.46,77.86,78.05,78.56,79.23,79.58,80.16,79.94,80.11,Papua,Kab/Kota,Indeks Pembangunan Manusia,-2.64647,140.777790
2744,Indonesia,66.53,67.09,67.70,68.31,68.90,69.55,70.18,70.81,71.39,71.92,71.94,72.29,Indonesia,Indonesia,Indeks Pembangunan Manusia,-6.20000,106.816666

In [ ]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2745 entries, 0 to 2744
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Provinsi/Kabupaten/Kota  2745 non-null   object
 1   2010                     2745 non-null   object
 2   2011                     2745 non-null   float64
 3   2012                     2745 non-null   float64
 4   2013                     2745 non-null   float64
 5   2014                     2745 non-null   float64
 6   2015                     2745 non-null   float64
 7   2016                     2745 non-null   float64
 8   2017                     2745 non-null   float64
 9   2018                     2745 non-null   float64
 10  2019                     2745 non-null   float64
 11  2020                     2745 non-null   float64
 12  2021                     2745 non-null   float64
 13  Provinsi                 2745 non-null   object
 14  Regional                 2745 non-null   object
 15  Komponen                 2745 non-null   object
 16  latitude                 2745 non-null   float64
 17  longitude                2745 non-null   float64
dtypes: float64(13), object(5)
memory usage: 386.1+ KB

In [ ]:
df_full.to_excel('df_full.xlsx', index = False, header=True)
files.download('df_full.xlsx')